/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface InvestmentLibraryInterface extends utils.Interface {
  functions: {
    "PERCENTAGE_PRECISION()": FunctionFragment;
    "PROPOSALID_PREFIX()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "PERCENTAGE_PRECISION" | "PROPOSALID_PREFIX"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PERCENTAGE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSALID_PREFIX",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PERCENTAGE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSALID_PREFIX",
    data: BytesLike
  ): Result;

  events: {};
}

export interface InvestmentLibrary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InvestmentLibraryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PERCENTAGE_PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    PROPOSALID_PREFIX(overrides?: CallOverrides): Promise<[string]>;
  };

  PERCENTAGE_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  PROPOSALID_PREFIX(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    PERCENTAGE_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    PROPOSALID_PREFIX(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    PERCENTAGE_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    PROPOSALID_PREFIX(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PERCENTAGE_PRECISION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PROPOSALID_PREFIX(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
