/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface FlexAllocationAdapterContractInterface
  extends utils.Interface {
  functions: {
    "allocateProjectToken(address,address,address,bytes32,uint256[5])": FunctionFragment;
    "configureDao(address,uint256,uint256)": FunctionFragment;
    "getInvestmentRewards(address,bytes32,address,uint256)": FunctionFragment;
    "getProposerBonus(address,bytes32,uint256)": FunctionFragment;
    "ifEligible(address,bytes32,address)": FunctionFragment;
    "isNFTMinted(address,bytes32,address)": FunctionFragment;
    "isVestCreated(address,bytes32,address)": FunctionFragment;
    "nftMinted(address,bytes32,address)": FunctionFragment;
    "noEscrow(address,bytes32)": FunctionFragment;
    "vestCreated(address,bytes32,address)": FunctionFragment;
    "vestingInfos(address,bytes32,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allocateProjectToken"
      | "configureDao"
      | "getInvestmentRewards"
      | "getProposerBonus"
      | "ifEligible"
      | "isNFTMinted"
      | "isVestCreated"
      | "nftMinted"
      | "noEscrow"
      | "vestCreated"
      | "vestingInfos"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allocateProjectToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "configureDao",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestmentRewards",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposerBonus",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ifEligible",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isNFTMinted",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isVestCreated",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nftMinted",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "noEscrow",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "vestCreated",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingInfos",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "allocateProjectToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureDao",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestmentRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposerBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ifEligible", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNFTMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVestCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftMinted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vestCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingInfos",
    data: BytesLike
  ): Result;

  events: {
    "AllocateToken(bytes32,address,address,address[])": EventFragment;
    "ConfigureDao(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AllocateToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConfigureDao"): EventFragment;
}

export interface AllocateTokenEventObject {
  proposalId: string;
  daoAddr: string;
  proposer: string;
  lps: string[];
}
export type AllocateTokenEvent = TypedEvent<
  [string, string, string, string[]],
  AllocateTokenEventObject
>;

export type AllocateTokenEventFilter = TypedEventFilter<AllocateTokenEvent>;

export interface ConfigureDaoEventObject {
  gpAllocationBonusRadio: BigNumber;
  riceStakeAllocationRadio: BigNumber;
}
export type ConfigureDaoEvent = TypedEvent<
  [BigNumber, BigNumber],
  ConfigureDaoEventObject
>;

export type ConfigureDaoEventFilter = TypedEventFilter<ConfigureDaoEvent>;

export interface FlexAllocationAdapterContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FlexAllocationAdapterContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allocateProjectToken(
      dao: PromiseOrValue<string>,
      tokenAddress: PromiseOrValue<string>,
      proposerAddr: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      uint256Args: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    configureDao(
      dao: PromiseOrValue<string>,
      gpAllocationBonusRadio: PromiseOrValue<BigNumberish>,
      riceStakeAllocationRadio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getInvestmentRewards(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      investor: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getProposerBonus(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    ifEligible(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isNFTMinted(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recepient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isVestCreated(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recepient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    nftMinted(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    noEscrow(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vestCreated(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vestingInfos(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean] & { tokenAmount: BigNumber; created: boolean }
    >;
  };

  allocateProjectToken(
    dao: PromiseOrValue<string>,
    tokenAddress: PromiseOrValue<string>,
    proposerAddr: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    uint256Args: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  configureDao(
    dao: PromiseOrValue<string>,
    gpAllocationBonusRadio: PromiseOrValue<BigNumberish>,
    riceStakeAllocationRadio: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getInvestmentRewards(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    investor: PromiseOrValue<string>,
    tokenAmount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getProposerBonus(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    tokenAmount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ifEligible(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    recipient: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isNFTMinted(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    recepient: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isVestCreated(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    recepient: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  nftMinted(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  noEscrow(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vestCreated(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vestingInfos(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BytesLike>,
    arg2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean] & { tokenAmount: BigNumber; created: boolean }
  >;

  callStatic: {
    allocateProjectToken(
      dao: PromiseOrValue<string>,
      tokenAddress: PromiseOrValue<string>,
      proposerAddr: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      uint256Args: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: CallOverrides
    ): Promise<void>;

    configureDao(
      dao: PromiseOrValue<string>,
      gpAllocationBonusRadio: PromiseOrValue<BigNumberish>,
      riceStakeAllocationRadio: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getInvestmentRewards(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      investor: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposerBonus(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ifEligible(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isNFTMinted(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recepient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isVestCreated(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recepient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    nftMinted(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    noEscrow(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    vestCreated(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    vestingInfos(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean] & { tokenAmount: BigNumber; created: boolean }
    >;
  };

  filters: {
    "AllocateToken(bytes32,address,address,address[])"(
      proposalId?: null,
      daoAddr?: null,
      proposer?: null,
      lps?: null
    ): AllocateTokenEventFilter;
    AllocateToken(
      proposalId?: null,
      daoAddr?: null,
      proposer?: null,
      lps?: null
    ): AllocateTokenEventFilter;

    "ConfigureDao(uint256,uint256)"(
      gpAllocationBonusRadio?: null,
      riceStakeAllocationRadio?: null
    ): ConfigureDaoEventFilter;
    ConfigureDao(
      gpAllocationBonusRadio?: null,
      riceStakeAllocationRadio?: null
    ): ConfigureDaoEventFilter;
  };

  estimateGas: {
    allocateProjectToken(
      dao: PromiseOrValue<string>,
      tokenAddress: PromiseOrValue<string>,
      proposerAddr: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      uint256Args: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    configureDao(
      dao: PromiseOrValue<string>,
      gpAllocationBonusRadio: PromiseOrValue<BigNumberish>,
      riceStakeAllocationRadio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getInvestmentRewards(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      investor: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposerBonus(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ifEligible(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isNFTMinted(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recepient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isVestCreated(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recepient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nftMinted(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    noEscrow(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vestCreated(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vestingInfos(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allocateProjectToken(
      dao: PromiseOrValue<string>,
      tokenAddress: PromiseOrValue<string>,
      proposerAddr: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      uint256Args: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    configureDao(
      dao: PromiseOrValue<string>,
      gpAllocationBonusRadio: PromiseOrValue<BigNumberish>,
      riceStakeAllocationRadio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getInvestmentRewards(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      investor: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposerBonus(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ifEligible(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isNFTMinted(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recepient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isVestCreated(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recepient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nftMinted(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    noEscrow(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vestCreated(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vestingInfos(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
