/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICollectiveVoting,
  ICollectiveVotingInterface,
} from "../../../../../contracts/collective/adapters/interfaces/ICollectiveVoting";

const _abi = [
  {
    inputs: [],
    name: "getAdapterName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract DaoRegistry",
        name: "dao",
        type: "address",
      },
      {
        internalType: "address",
        name: "actionId",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "getSenderAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract DaoRegistry",
        name: "dao",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "proposalId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "startNewVotingForProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract DaoRegistry",
        name: "dao",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "proposalId",
        type: "bytes32",
      },
    ],
    name: "voteResult",
    outputs: [
      {
        internalType: "enum ICollectiveVoting.VotingState",
        name: "state",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "nbYes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nbNo",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICollectiveVoting__factory {
  static readonly abi = _abi;
  static createInterface(): ICollectiveVotingInterface {
    return new utils.Interface(_abi) as ICollectiveVotingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICollectiveVoting {
    return new Contract(address, _abi, signerOrProvider) as ICollectiveVoting;
  }
}
