/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ColletiveGovernorInProposalContract__factory } from "./ColletiveGovernorInProposalContract__factory";
