/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CollectiveDistributeAdatperContract__factory } from "./CollectiveDistributeAdatperContract__factory";
