/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VintageInvestmentPaybackTokenAdapterContract__factory } from "./VintageInvestmentPaybackTokenAdapterContract__factory";
