/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ColletiveGovernorManagementAdapterContract__factory } from "./ColletiveGovernorManagementAdapterContract__factory";
