/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as executorSol from "./Executor.sol";
export type { executorSol };
import type * as executorFactorySol from "./ExecutorFactory.sol";
export type { executorFactorySol };
