/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace FlexDaosetLibrary {
  export type FlexDaoPollingInfoStruct = {
    votingPeriod: PromiseOrValue<BigNumberish>;
    votingPower: PromiseOrValue<BigNumberish>;
    superMajority: PromiseOrValue<BigNumberish>;
    quorum: PromiseOrValue<BigNumberish>;
    votingAssetType: PromiseOrValue<BigNumberish>;
    tokenAddress: PromiseOrValue<string>;
    tokenID: PromiseOrValue<BigNumberish>;
    supportType: PromiseOrValue<BigNumberish>;
    quorumType: PromiseOrValue<BigNumberish>;
  };

  export type FlexDaoPollingInfoStructOutput = [
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    votingPeriod: BigNumber;
    votingPower: number;
    superMajority: BigNumber;
    quorum: BigNumber;
    votingAssetType: BigNumber;
    tokenAddress: string;
    tokenID: BigNumber;
    supportType: BigNumber;
    quorumType: BigNumber;
  };

  export type FlexDaoPollVoterMembershipInfoStruct = {
    name: PromiseOrValue<string>;
    varifyType: PromiseOrValue<BigNumberish>;
    minHolding: PromiseOrValue<BigNumberish>;
    tokenAddress: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    whiteList: PromiseOrValue<string>[];
  };

  export type FlexDaoPollVoterMembershipInfoStructOutput = [
    string,
    number,
    BigNumber,
    string,
    BigNumber,
    string[]
  ] & {
    name: string;
    varifyType: number;
    minHolding: BigNumber;
    tokenAddress: string;
    tokenId: BigNumber;
    whiteList: string[];
  };

  export type PollForInvestmentParamsStruct = {
    dao: PromiseOrValue<string>;
    pollEnable: PromiseOrValue<boolean>;
    pollvoterMembership: FlexDaosetLibrary.FlexDaoPollVoterMembershipInfoStruct;
    pollingInfo: FlexDaosetLibrary.FlexDaoPollingInfoStruct;
  };

  export type PollForInvestmentParamsStructOutput = [
    string,
    boolean,
    FlexDaosetLibrary.FlexDaoPollVoterMembershipInfoStructOutput,
    FlexDaosetLibrary.FlexDaoPollingInfoStructOutput
  ] & {
    dao: string;
    pollEnable: boolean;
    pollvoterMembership: FlexDaosetLibrary.FlexDaoPollVoterMembershipInfoStructOutput;
    pollingInfo: FlexDaosetLibrary.FlexDaoPollingInfoStructOutput;
  };
}

export interface FlexDaoSetPollingAdapterContractInterface
  extends utils.Interface {
  functions: {
    "getWhitelist(bytes32)": FunctionFragment;
    "isActiveMember(address,address)": FunctionFragment;
    "ongoingPollForInvestmentProposal(address)": FunctionFragment;
    "pollForInvestmentProposals(address,bytes32)": FunctionFragment;
    "processPollForInvestmentProposal(address,bytes32)": FunctionFragment;
    "submitPollForInvestmentProposal((address,bool,(string,uint8,uint256,address,uint256,address[]),(uint256,uint8,uint256,uint256,uint256,address,uint256,uint256,uint256)))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getWhitelist"
      | "isActiveMember"
      | "ongoingPollForInvestmentProposal"
      | "pollForInvestmentProposals"
      | "processPollForInvestmentProposal"
      | "submitPollForInvestmentProposal"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getWhitelist",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveMember",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "ongoingPollForInvestmentProposal",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "pollForInvestmentProposals",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "processPollForInvestmentProposal",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPollForInvestmentProposal",
    values: [FlexDaosetLibrary.PollForInvestmentParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ongoingPollForInvestmentProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pollForInvestmentProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processPollForInvestmentProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPollForInvestmentProposal",
    data: BytesLike
  ): Result;

  events: {
    "ProposalCreated(address,bytes32,uint8)": EventFragment;
    "ProposalProcessed(address,bytes32,uint256,uint128,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalProcessed"): EventFragment;
}

export interface ProposalCreatedEventObject {
  daoAddr: string;
  proposalId: string;
  pType: number;
}
export type ProposalCreatedEvent = TypedEvent<
  [string, string, number],
  ProposalCreatedEventObject
>;

export type ProposalCreatedEventFilter = TypedEventFilter<ProposalCreatedEvent>;

export interface ProposalProcessedEventObject {
  daoAddr: string;
  proposalId: string;
  voteResult: BigNumber;
  allVotingWeight: BigNumber;
  nbYes: BigNumber;
  nbNo: BigNumber;
}
export type ProposalProcessedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, BigNumber],
  ProposalProcessedEventObject
>;

export type ProposalProcessedEventFilter =
  TypedEventFilter<ProposalProcessedEvent>;

export interface FlexDaoSetPollingAdapterContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FlexDaoSetPollingAdapterContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getWhitelist(
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    isActiveMember(
      dao: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    ongoingPollForInvestmentProposal(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    pollForInvestmentProposals(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        string,
        number,
        BigNumber,
        string,
        BigNumber,
        FlexDaosetLibrary.FlexDaoPollingInfoStructOutput,
        BigNumber,
        BigNumber,
        number
      ] & {
        pollEnable: boolean;
        name: string;
        varifyType: number;
        minHolding: BigNumber;
        tokenAddress: string;
        tokenId: BigNumber;
        pollingInfo: FlexDaosetLibrary.FlexDaoPollingInfoStructOutput;
        creationTime: BigNumber;
        stopVoteTime: BigNumber;
        state: number;
      }
    >;

    processPollForInvestmentProposal(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitPollForInvestmentProposal(
      params: FlexDaosetLibrary.PollForInvestmentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getWhitelist(
    proposalId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  isActiveMember(
    dao: PromiseOrValue<string>,
    _addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  ongoingPollForInvestmentProposal(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  pollForInvestmentProposals(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [
      boolean,
      string,
      number,
      BigNumber,
      string,
      BigNumber,
      FlexDaosetLibrary.FlexDaoPollingInfoStructOutput,
      BigNumber,
      BigNumber,
      number
    ] & {
      pollEnable: boolean;
      name: string;
      varifyType: number;
      minHolding: BigNumber;
      tokenAddress: string;
      tokenId: BigNumber;
      pollingInfo: FlexDaosetLibrary.FlexDaoPollingInfoStructOutput;
      creationTime: BigNumber;
      stopVoteTime: BigNumber;
      state: number;
    }
  >;

  processPollForInvestmentProposal(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitPollForInvestmentProposal(
    params: FlexDaosetLibrary.PollForInvestmentParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getWhitelist(
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    isActiveMember(
      dao: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    ongoingPollForInvestmentProposal(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    pollForInvestmentProposals(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        string,
        number,
        BigNumber,
        string,
        BigNumber,
        FlexDaosetLibrary.FlexDaoPollingInfoStructOutput,
        BigNumber,
        BigNumber,
        number
      ] & {
        pollEnable: boolean;
        name: string;
        varifyType: number;
        minHolding: BigNumber;
        tokenAddress: string;
        tokenId: BigNumber;
        pollingInfo: FlexDaosetLibrary.FlexDaoPollingInfoStructOutput;
        creationTime: BigNumber;
        stopVoteTime: BigNumber;
        state: number;
      }
    >;

    processPollForInvestmentProposal(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    submitPollForInvestmentProposal(
      params: FlexDaosetLibrary.PollForInvestmentParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ProposalCreated(address,bytes32,uint8)"(
      daoAddr?: null,
      proposalId?: null,
      pType?: null
    ): ProposalCreatedEventFilter;
    ProposalCreated(
      daoAddr?: null,
      proposalId?: null,
      pType?: null
    ): ProposalCreatedEventFilter;

    "ProposalProcessed(address,bytes32,uint256,uint128,uint256,uint256)"(
      daoAddr?: null,
      proposalId?: null,
      voteResult?: null,
      allVotingWeight?: null,
      nbYes?: null,
      nbNo?: null
    ): ProposalProcessedEventFilter;
    ProposalProcessed(
      daoAddr?: null,
      proposalId?: null,
      voteResult?: null,
      allVotingWeight?: null,
      nbYes?: null,
      nbNo?: null
    ): ProposalProcessedEventFilter;
  };

  estimateGas: {
    getWhitelist(
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isActiveMember(
      dao: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ongoingPollForInvestmentProposal(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pollForInvestmentProposals(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    processPollForInvestmentProposal(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitPollForInvestmentProposal(
      params: FlexDaosetLibrary.PollForInvestmentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getWhitelist(
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isActiveMember(
      dao: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ongoingPollForInvestmentProposal(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pollForInvestmentProposals(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    processPollForInvestmentProposal(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitPollForInvestmentProposal(
      params: FlexDaosetLibrary.PollForInvestmentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
