/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface ICollectiveFundRaiseInterface extends utils.Interface {
  functions: {};

  events: {
    "ProposalCreated(address,bytes32)": EventFragment;
    "proposalExecuted(address,bytes32,uint8,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "proposalExecuted"): EventFragment;
}

export interface ProposalCreatedEventObject {
  daoAddr: string;
  proposalId: string;
}
export type ProposalCreatedEvent = TypedEvent<
  [string, string],
  ProposalCreatedEventObject
>;

export type ProposalCreatedEventFilter = TypedEventFilter<ProposalCreatedEvent>;

export interface proposalExecutedEventObject {
  daoAddr: string;
  proposalId: string;
  state: number;
  allVotingWeight: BigNumber;
  nbYes: BigNumber;
  nbNo: BigNumber;
  voteResult: BigNumber;
}
export type proposalExecutedEvent = TypedEvent<
  [string, string, number, BigNumber, BigNumber, BigNumber, BigNumber],
  proposalExecutedEventObject
>;

export type proposalExecutedEventFilter =
  TypedEventFilter<proposalExecutedEvent>;

export interface ICollectiveFundRaise extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICollectiveFundRaiseInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ProposalCreated(address,bytes32)"(
      daoAddr?: null,
      proposalId?: null
    ): ProposalCreatedEventFilter;
    ProposalCreated(
      daoAddr?: null,
      proposalId?: null
    ): ProposalCreatedEventFilter;

    "proposalExecuted(address,bytes32,uint8,uint256,uint256,uint256,uint256)"(
      daoAddr?: null,
      proposalId?: null,
      state?: null,
      allVotingWeight?: null,
      nbYes?: null,
      nbNo?: null,
      voteResult?: null
    ): proposalExecutedEventFilter;
    proposalExecuted(
      daoAddr?: null,
      proposalId?: null,
      state?: null,
      allVotingWeight?: null,
      nbYes?: null,
      nbNo?: null,
      voteResult?: null
    ): proposalExecutedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
