/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IFlexFunding {
  export type InvestmentInfoStruct = {
    tokenAddress: PromiseOrValue<string>;
    minInvestmentAmount: PromiseOrValue<BigNumberish>;
    maxInvestmentAmount: PromiseOrValue<BigNumberish>;
    escrow: PromiseOrValue<boolean>;
    paybackTokenAddr: PromiseOrValue<string>;
    paybackTokenAmount: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    minReturnAmount: PromiseOrValue<BigNumberish>;
    maxReturnAmount: PromiseOrValue<BigNumberish>;
    approverAddr: PromiseOrValue<string>;
    recipientAddr: PromiseOrValue<string>;
  };

  export type InvestmentInfoStructOutput = [
    string,
    BigNumber,
    BigNumber,
    boolean,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string
  ] & {
    tokenAddress: string;
    minInvestmentAmount: BigNumber;
    maxInvestmentAmount: BigNumber;
    escrow: boolean;
    paybackTokenAddr: string;
    paybackTokenAmount: BigNumber;
    price: BigNumber;
    minReturnAmount: BigNumber;
    maxReturnAmount: BigNumber;
    approverAddr: string;
    recipientAddr: string;
  };

  export type VestInfoStruct = {
    vestingStartTime: PromiseOrValue<BigNumberish>;
    vestingCliffEndTime: PromiseOrValue<BigNumberish>;
    vestingEndTime: PromiseOrValue<BigNumberish>;
    vestingInterval: PromiseOrValue<BigNumberish>;
    vestingCliffLockAmount: PromiseOrValue<BigNumberish>;
    nftEnable: PromiseOrValue<boolean>;
    erc721: PromiseOrValue<string>;
    vestName: PromiseOrValue<string>;
    vestDescription: PromiseOrValue<string>;
  };

  export type VestInfoStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    string,
    string,
    string
  ] & {
    vestingStartTime: BigNumber;
    vestingCliffEndTime: BigNumber;
    vestingEndTime: BigNumber;
    vestingInterval: BigNumber;
    vestingCliffLockAmount: BigNumber;
    nftEnable: boolean;
    erc721: string;
    vestName: string;
    vestDescription: string;
  };

  export type InvestorIdentificationInfoStruct = {
    bType: PromiseOrValue<BigNumberish>;
    bChainId: PromiseOrValue<BigNumberish>;
    bTokanAddr: PromiseOrValue<string>;
    bTokenId: PromiseOrValue<BigNumberish>;
    bMinHoldingAmount: PromiseOrValue<BigNumberish>;
  };

  export type InvestorIdentificationInfoStructOutput = [
    number,
    number,
    string,
    BigNumber,
    BigNumber
  ] & {
    bType: number;
    bChainId: number;
    bTokanAddr: string;
    bTokenId: BigNumber;
    bMinHoldingAmount: BigNumber;
  };

  export type PriorityDepositInfoStruct = {
    enable: PromiseOrValue<boolean>;
    pType: PromiseOrValue<BigNumberish>;
    token: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type PriorityDepositInfoStructOutput = [
    boolean,
    number,
    string,
    BigNumber,
    BigNumber
  ] & {
    enable: boolean;
    pType: number;
    token: string;
    tokenId: BigNumber;
    amount: BigNumber;
  };

  export type FundRaiseInfoStruct = {
    fundRaiseType: PromiseOrValue<BigNumberish>;
    fundRaiseStartTime: PromiseOrValue<BigNumberish>;
    fundRaiseEndTime: PromiseOrValue<BigNumberish>;
    minDepositAmount: PromiseOrValue<BigNumberish>;
    maxDepositAmount: PromiseOrValue<BigNumberish>;
    investorIdentification: PromiseOrValue<boolean>;
    investorIdentificationInfo: IFlexFunding.InvestorIdentificationInfoStruct;
    priorityDepositInfo: IFlexFunding.PriorityDepositInfoStruct;
  };

  export type FundRaiseInfoStructOutput = [
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    IFlexFunding.InvestorIdentificationInfoStructOutput,
    IFlexFunding.PriorityDepositInfoStructOutput
  ] & {
    fundRaiseType: number;
    fundRaiseStartTime: BigNumber;
    fundRaiseEndTime: BigNumber;
    minDepositAmount: BigNumber;
    maxDepositAmount: BigNumber;
    investorIdentification: boolean;
    investorIdentificationInfo: IFlexFunding.InvestorIdentificationInfoStructOutput;
    priorityDepositInfo: IFlexFunding.PriorityDepositInfoStructOutput;
  };

  export type ProposerRewardInfoStruct = {
    tokenRewardAmount: PromiseOrValue<BigNumberish>;
    cashRewardAmount: PromiseOrValue<BigNumberish>;
  };

  export type ProposerRewardInfoStructOutput = [BigNumber, BigNumber] & {
    tokenRewardAmount: BigNumber;
    cashRewardAmount: BigNumber;
  };

  export type ProposalParamsStruct = {
    investmentInfo: IFlexFunding.InvestmentInfoStruct;
    vestInfo: IFlexFunding.VestInfoStruct;
    fundRaiseInfo: IFlexFunding.FundRaiseInfoStruct;
    proposerRewardInfo: IFlexFunding.ProposerRewardInfoStruct;
    priorityDepositWhitelist: PromiseOrValue<string>[];
  };

  export type ProposalParamsStructOutput = [
    IFlexFunding.InvestmentInfoStructOutput,
    IFlexFunding.VestInfoStructOutput,
    IFlexFunding.FundRaiseInfoStructOutput,
    IFlexFunding.ProposerRewardInfoStructOutput,
    string[]
  ] & {
    investmentInfo: IFlexFunding.InvestmentInfoStructOutput;
    vestInfo: IFlexFunding.VestInfoStructOutput;
    fundRaiseInfo: IFlexFunding.FundRaiseInfoStructOutput;
    proposerRewardInfo: IFlexFunding.ProposerRewardInfoStructOutput;
    priorityDepositWhitelist: string[];
  };
}

export interface IFlexFundingInterface extends utils.Interface {
  functions: {
    "processProposal(address,bytes32)": FunctionFragment;
    "submitProposal(address,((address,uint256,uint256,bool,address,uint256,uint256,uint256,uint256,address,address),(uint256,uint256,uint256,uint256,uint256,bool,address,string,string),(uint8,uint256,uint256,uint256,uint256,bool,(uint8,uint32,address,uint256,uint256),(bool,uint8,address,uint256,uint256)),(uint256,uint256),address[]))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "processProposal" | "submitProposal"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "processProposal",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProposal",
    values: [PromiseOrValue<string>, IFlexFunding.ProposalParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "processProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProposal",
    data: BytesLike
  ): Result;

  events: {
    "ProposalCreated(address,bytes32,address)": EventFragment;
    "ProposalExecuted(address,bytes32,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalExecuted"): EventFragment;
}

export interface ProposalCreatedEventObject {
  daoAddress: string;
  proposalId: string;
  proposer: string;
}
export type ProposalCreatedEvent = TypedEvent<
  [string, string, string],
  ProposalCreatedEventObject
>;

export type ProposalCreatedEventFilter = TypedEventFilter<ProposalCreatedEvent>;

export interface ProposalExecutedEventObject {
  daoAddress: string;
  proposalId: string;
  state: number;
}
export type ProposalExecutedEvent = TypedEvent<
  [string, string, number],
  ProposalExecutedEventObject
>;

export type ProposalExecutedEventFilter =
  TypedEventFilter<ProposalExecutedEvent>;

export interface IFlexFunding extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFlexFundingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    processProposal(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitProposal(
      dao: PromiseOrValue<string>,
      params: IFlexFunding.ProposalParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  processProposal(
    dao: PromiseOrValue<string>,
    proposalId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitProposal(
    dao: PromiseOrValue<string>,
    params: IFlexFunding.ProposalParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    processProposal(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    submitProposal(
      dao: PromiseOrValue<string>,
      params: IFlexFunding.ProposalParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ProposalCreated(address,bytes32,address)"(
      daoAddress?: null,
      proposalId?: null,
      proposer?: null
    ): ProposalCreatedEventFilter;
    ProposalCreated(
      daoAddress?: null,
      proposalId?: null,
      proposer?: null
    ): ProposalCreatedEventFilter;

    "ProposalExecuted(address,bytes32,uint8)"(
      daoAddress?: null,
      proposalId?: null,
      state?: null
    ): ProposalExecutedEventFilter;
    ProposalExecuted(
      daoAddress?: null,
      proposalId?: null,
      state?: null
    ): ProposalExecutedEventFilter;
  };

  estimateGas: {
    processProposal(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitProposal(
      dao: PromiseOrValue<string>,
      params: IFlexFunding.ProposalParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    processProposal(
      dao: PromiseOrValue<string>,
      proposalId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitProposal(
      dao: PromiseOrValue<string>,
      params: IFlexFunding.ProposalParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
