/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFlexDaoset } from "./IFlexDaoset";
export type { IFlexFunding } from "./IFlexFunding";
export type { IFlexVesting } from "./IFlexVesting";
export type { IFlexVoting } from "./IFlexVoting";
